
DROP DATABASE IF EXISTS TestingSystem;
CREATE DATABASE IF NOT EXISTS TestingSystem;
USE TestingSystem;



CREATE TABLE Department(
	DepartmentID 		TINYINT AUTO_INCREMENT PRIMARY KEY,
    DepartmentName 		VARCHAR(50)NOT NULL UNIQUE KEY
);


CREATE TABLE `Position`(
	PositionID			TINYINT AUTO_INCREMENT PRIMARY KEY,
    PositionName		ENUM('Dev','Test', 'Scrum Master', 'PM')
);


CREATE TABLE `Account`(
	AccountID			SMALLINT AUTO_INCREMENT PRIMARY KEY,
    Email				VARCHAR(50) NOT  NULL UNIQUE KEY,
    User_name			VARCHAR(50) NOT NULL,
    Full_Name			NVARCHAR(50) NOT NULL,
    DepartmentID 		TINYINT NOT NULL,
    PositionID			TINYINT NOT NULL,
    CreateDATE			DATE,
    FOREIGN KEY  (DepartmentID) REFERENCES Department (DepartmentID),
	FOREIGN KEY  (PositionID)   REFERENCES Position (PositionID)
);


CREATE TABLE `Group`(
	GroupID				TINYINT AUTO_INCREMENT PRIMARY KEY,
    GroupName			VARCHAR(50) NOT NULL UNIQUE KEY,
    CreatorID			SMALLINT NOT NULL,
    CreateDATE			DATE ,
    FOREIGN KEY  (CREATORID)  REFERENCES ACCOUNT(ACCOUNTID)
);


CREATE TABLE GroupAccount(
	GroupID				TINYINT ,
    AccountID			SMALLINT NOT NULL,
    JoinDATE			DATE,
    PRIMARY KEY(GROUPID,ACCOUNTID),
    FOREIGN KEY (GROUPID)  REFERENCES `Group` (GROUPID),
    FOREIGN KEY (ACCOUNTID) REFERENCES `Account`(ACCOUNTID)
);


CREATE TABLE TypeQuestion (
    TypeID 	TINYINT AUTO_INCREMENT PRIMARY KEY,
    TypeName ENUM('ESSAY','MULTIPLE-CHOICE')
);


CREATE TABLE CategoryQuestion(
    CategoryID			TINYINT AUTO_INCREMENT PRIMARY KEY,
    CategoryName		NVARCHAR(50) NOT NULL
);


CREATE TABLE Question(
    QuestionID			SMALLINT AUTO_INCREMENT PRIMARY KEY,
    Content				TEXT,
    CategoryID			TINYINT ,
    TypeID				TINYINT ,
    CreatorID			SMALLINT,
    CreateDATE			DATE,
    FOREIGN KEY (TypeID) REFERENCES TYPEQUESTION(TypeID),
    FOREIGN KEY (CreatorID)  REFERENCES `ACCOUNT`(AccountID),
    FOREIGN KEY (CATEGORYID) REFERENCES CategoryQuestion(CATEGORYID)
);


CREATE TABLE Answer(
    Answers				SMALLINT AUTO_INCREMENT PRIMARY KEY,
    Content				VARCHAR(50),
    QuestionID			SMALLINT ,
    isCorrect			BOOLEAN,
    -- BIT,BOOLEAN
    FOREIGN KEY  (QuestionID) REFERENCES QUESTION (QuestionID)
);


CREATE TABLE Exam(
    ExamID				SMALLINT AUTO_INCREMENT PRIMARY KEY,
    `Code`				VARCHAR(50) NOT NULL,
    Title				NVARCHAR(50) NOT NULL,
    CategoryID			TINYINT  NOT NULL,
    Duration			TINYINT UNSIGNED NOT NULL,
    CreatorID			SMALLINT  NOT NULL,
    CreateDATE			DATE,
    FOREIGN KEY  (CategoryID) REFERENCES CategoryQuestion (CategoryID),
    FOREIGN KEY  (CreatorID) REFERENCES `ACCOUNT` (accountID)
);


CREATE TABLE ExamQuestion(
    ExamID			SMALLINT  NOT NULL,
	QuestionID		SMALLINT  NOT NULL,
    PRIMARY KEY(EXAMID,QUESTIONID),
    FOREIGN KEY  (QUESTIONID) REFERENCES QUESTION (QUESTIONID),
     FOREIGN KEY (EXAMID)   REFERENCES EXAM (EXAMID)
);

